# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install

before_install:
  - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
  - output=$(php php-cs-fixer.phar fix -v --dry-run .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
  - phpunit
